FROM mcr.microsoft.com/windows/nanoserver:ltsc2025

ARG NODE_VERSION=22.14.0

WORKDIR C:/app

ADD https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-win-x64.zip C:/node.zip

RUN tar -xf C:/node.zip -C C:/ && move C:\node-v%NODE_VERSION%-win-x64 C:\nodejs && del C:/node.zip

ENV PATH=C:/nodejs

COPY package.json ./
COPY dist ./dist
COPY Backend ./Backend
COPY public ./public
COPY index.html ./
COPY node_modules ./node_modules

ENV NODE_ENV=production
ENV PORT=3000

EXPOSE 3000

CMD ["C:\\nodejs\\node.exe", "dist\\server.cjs"]
